version: '3'
services:
  geth:
    image: ethereum/client-go:v1.10.26
    command: 
      --miner.gaslimit 12000000
      --http
      --http.api personal,eth,net,web3,debug
      --http.vhosts '*,localhost,host.docker.internal'
      --http.addr "0.0.0.0"
      --ignore-legacy-receipts
      --allow-insecure-unlock
      --rpc.allow-unprotected-txs
      --dev
      --verbosity 3
      --nodiscover
      --maxpeers 0
      --mine
      --miner.threads 1
      --networkid 1337
      --ipcpath /root/.ethereum/geth.ipc
    ports:
      - 8545:8545
    network_mode: bridge
